### ISSUE TITLE
Move out functionally different decorators into a file each

### ISSUE THREAD

**Issue by Makman2** [coala/coala-decorators-USE-cOALA-UTILS-INSTEAD#6]
Improves maintenance^^

We should import them into `__init__.py` then :+1:

**Comment by AbdealiJK** [comment]
I agree :) I was wondering why there was `coala-decorators.Decorators, felt redundant.

**Comment by sils1297** [comment]
I'd just throw everythin in the `__init__`

**Comment by jayvdb** [comment]
Stale.
