### ISSUE TITLE
Tests Tests Tests and CI

### ISSUE THREAD

**Issue by AbdealiJK** [coala/coala-decorators-USE-cOALA-UTILS-INSTEAD#9]
We should not merge https://github.com/coala-analyzer/coala/pull/2136 until the tests are ready. There is already https://github.com/coala-analyzer/coala/blob/master/tests/misc/DecoratorsTest.py which makes it pretty easy. Few modifications may be needed to get 100% coverage though.

With tests, we also need CI :) And as `coala` supports Windows, Unix, OSX, we need all three here ^_^

**Comment by AbdealiJK** [comment]
Note: You may want to try making doctests here are decorators are pretty modular and easy to test for ?
(If possible)

**Comment by sils1297** [comment]
only linux and windows suffice, we may drop dedicated osx testing anyway soon

**Comment by sils1297** [comment]
@Adrianzatreanu can you look at this ASAP?

**Comment by Adrianzatreanu** [comment]
sure, taking a look over this right now

**Comment by Adrianzatreanu** [comment]
assigning as per gitter discussion.

**Comment by jayvdb** [comment]
This was done
